name: CI-Main-Workflow

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: 

jobs:
  build: 
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v5
        
      - run: ci/build-app.sh

      - name: run a one-line script
        run: echo Hello World

      - name: run a multi-line script
        run: |
          echo Add other actions
          echo to build bla bla
